server:
  port: 8010
  forward-headers-strategy: true
  servlet:
    session:
      timeout: 86400
    context-path: /mall
spring:
  transaction:
    rollback-on-commit-failure: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/uzymall?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#    static-path-pattern: /WEB-INF/static/
#mybatis:
#  type-aliases-package: com.uzykj.mall.entity
#  mapperLocations: classpath*:/mapper/**Mapper.xml
#  config-location: classpath*:/mapper/**Mapper.xml
#  configuration:
#    mapUnderscoreToCamelCase: true  # 驼峰转换

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.uzykj.mall.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
#    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file: ./logs/app.log
  level:
    org:
      springframework:
        boot:
          autoconfigure: error